#######

  # The cloud-init script you provided will do the following:
    # Update and upgrade the system packages.
    # Install the git package.
    # Install Ansible using the distro installation method and the ansible package name.
    # Pull the Ansible playbook from the https://github.com/intel/optimized-cloud-recipes.git repository and execute the recipes/sqlite-flask-sgx-ubuntu/gramine.recipe.yml playbook.
 
  # To learn more about Cloud - Init : https://cloudinit.readthedocs.io/en/latest/index.html
#######

#cloud-config
package_update: true
package_upgrade: true

package:
  - git

runcmd:
  - sudo apt install git -y
  - sudo apt install software-properties-common
  - sudo add-apt-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible -y
  - git clone https://github.com/intel/optimized-cloud-recipes.git /tmp/optimized-cloud-recipes
  - cd /tmp/optimized-cloud-recipes/recipes/intel-azure-linux-tdx-ita
  - cp ita-yml /tmp/ita-recipe.yml
  - echo 'export tustauthority_api_key=${trustauthority_api_key}' | sudo tee -a /tmp/ita-recipe.yml
  - chmod +x /tmp/ita-recipe.yml
  - source /tmp/ita-recipe.yml
  - ansible-playbook ita-recipe.yml

  

